### ISSUE TITLE
No such command Tauri error

### ISSUE THREAD

**Issue by Tony20221** [MindWorkAI/AI-Studio#103]
I ran the nu build.nu publish command and I saw this error:

![image](https://github.com/user-attachments/assets/25c561f5-1a5a-4344-9e64-5b339f53f78d)

Also there's no 'target' folder under runtime folder.

**Comment by SommerEngineering** [comment]
Thank you @Tony20221 for bringing this to my attention. Indeed, I had forgotten to set up Tauri in the documentation. With PR #107 and the commit https://github.com/SommerEngineering/AI-Studio/commit/d826aaef9a28758ce0032a74d88a70c95aa52fbb, this has been corrected. You need to meet the prerequisites for [Tauri](https://tauri.app/v1/guides/getting-started/prerequisites/) (depending on the operating system) and then install the CLI tools from Tauri with `cargo install tauri-cli`. You can ignore the instructions for Node.js in the Tauri prerequisites since we do not use Node.js. The build instructions in the repo have now been updated. Thanks again for the hint.

Regarding the `target` folder: It should be automatically generated by the Rust compiler later, once the compile process runs.
