### ISSUE TITLE
Host.cs needs updating. v1 -> api for Ollama usage

### ISSUE THREAD

**Issue by kabuki4774** [MindWorkAI/AI-Studio#171]

**Comment by SommerEngineering** [comment]
Thank you very much for the issue @kabuki4774. Unfortunately, I can't do much with just the headline and have to speculate. Could you please explain what you mean? In what way should the `Host.cs` file be revised because of `ollama`? 

Do you mean that the `BaseURL` for `ollama` needs to be changed from `v1` to `api`? The `ollama` server offers two APIs: One based on OpenAI's API under `v1` (see [here](https://github.com/ollama/ollama/blob/main/docs/openai.md)) and its own API under `api` (see [here](https://github.com/ollama/ollama/blob/main/docs/api.md)). Currently, AI Studio uses the `v1` API. For the embeddings in the RAG implementation, we will probably also need to use the `ollama`-specific API.

**Comment by kabuki4774** [comment]
Apologies for the brevity but you are correct. Thanks for helping me understand my confusion.
